$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: diabetes-automated-pipeline

settings:
  default_compute: azureml:serverless

jobs:
  train_step:
    type: command
    # UPDATED: Upload the root folder and run train.py directly
    code: .
    command: python train.py
    environment: azureml://registries/azureml/environments/sklearn-1.5/labels/latest